# Generated by Django 2.1.2 on 2018-11-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='thumb',
            new_name='image',
        ),
    ]
