# Generated by Django 2.1.2 on 2019-04-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mplan_name', models.CharField(max_length=50)),
                ('mreq_num', models.IntegerField()),
                ('msub', models.CharField(max_length=30)),
                ('mnum', models.CharField(max_length=30)),
                ('mname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Option_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oplan_name', models.CharField(max_length=50)),
                ('oreq_num', models.IntegerField()),
                ('osub', models.CharField(max_length=30)),
                ('onum', models.CharField(max_length=30)),
                ('oname', models.CharField(max_length=30)),
            ],
        ),
    ]
