# Generated by Django 2.1.2 on 2018-10-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ctcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_year', models.CharField(max_length=10)),
                ('reg_semeter', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=30)),
            ],
        ),
    ]
