# Generated by Django 2.1.2 on 2018-10-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctcs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctcs',
            old_name='reg_semeter',
            new_name='Registration_semeter',
        ),
        migrations.RenameField(
            model_name='ctcs',
            old_name='reg_year',
            new_name='Registration_year',
        ),
    ]
