# Generated by Django 2.1.2 on 2018-10-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctcs', '0003_auto_20181029_0158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursesTaken',
        ),
    ]
